name: Daily Content Update

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC
  workflow_dispatch:      # Allows manual trigger from GitHub UI

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          
      - name: Update index with today's content
        run: |
          TODAY_ET=$(TZ='America/New_York' date +%Y-%m-%d)
          
          echo "Checking for file: archive/$TODAY_ET.html"
          
          if [ -f "archive/$TODAY_ET.html" ]; then
            cp "archive/$TODAY_ET.html" "index.html"
            git config --local user.email "github-actions@github.com"
            git config --local user.name "GitHub Actions"
            git add index.html
            git commit -m "Update index for $TODAY_ET"
            git push
          else
            echo "No content found for $TODAY_ET"
            exit 1
          fi
