name: Daily Content Update
on:
  schedule:
    - cron: '0 6 * * *'  # Run at midnight CST (6am UTC)
  workflow_dispatch:      # Allows manual trigger from GitHub UI

jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          
      - name: Update index with today's content
        run: |
          TODAY_CT=$(TZ='America/Chicago' date +%Y-%m-%d)
          
          echo "Checking for file: archive/$TODAY_CT.html"
          
          if [ -f "archive/$TODAY_CT.html" ]; then
            cp "archive/$TODAY_CT.html" "index.html"
            git config --local user.email "github-actions@github.com"
            git config --local user.name "GitHub Actions"
            git add index.html
            git commit -m "Update index for $TODAY_CT"
            git push
          else
            echo "No content found for $TODAY_CT"
            exit 1
          fi
