# .github/workflows/daily-update.yml
name: Daily Content Update

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC
  workflow_dispatch:      # Allows manual trigger from GitHub UI

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Update index with today's content
        run: |
          TODAY=$(date +%Y-%m-%d)
          if [ -f "archive/$TODAY.html" ]; then
            cp "archive/$TODAY.html" "index.html"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add index.html
            git commit -m "Update index for $TODAY"
            git push
          else
            echo "No content found for $TODAY"
            exit 1
          fi
